### ISSUE TITLE
[Feature request] Highlight escape sequences

### ISSUE THREAD

**Issue by kkanungo17** [alexanderbast/vscode-snazzy#1]
Escape sequences like \n and \s aren't highlighted in C code.

P.S. MATLAB highlighting too pls

**Comment by instaatze** [comment]
Thanks for the request!
Highlighting for escape sequences will be in the next update. I'll look into MATLAB support, but that seems to be a bigger task.

**Comment by instaatze** [comment]
I'm going to close this issue. Highlighting for escape sequences came in update [v2.7.0](https://github.com/alexanderbast/vscode-snazzy/releases/tag/v2.7.0).
Regarding MATLAB support, VS Code doesn't have MATLAB language support. There is a [MATLAB extension](https://github.com/Gimly/vscode-matlab) which gives a little bit of syntax definitions and therefor highlighting with this theme, but since I personally don't use MATLAB it's impossible for me to guess what should be colored in which way/different. Please provide an example file and comments in another issue if you want better highlighting for MATLAB.
